#!/usr/bin/env python3
"""Auto-fix lint errors using Claude Agent SDK."""

import os
import subprocess
import sys

from anthropic import Anthropic


def run_command(cmd: str, cwd: str = None) -> tuple[str, int]:
    """Run a shell command and return output and exit code."""
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True, cwd=cwd)
    return result.stdout + result.stderr, result.returncode


def main():
    # Check for API key
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("Error: ANTHROPIC_API_KEY not set")
        sys.exit(1)

    # Initialize Anthropic client
    client = Anthropic(api_key=api_key)

    # Run lint check to get errors
    print("Running ruff check...")
    lint_output, lint_code = run_command("ruff check backend --output-format=text")

    if lint_code == 0:
        print("✓ No lint errors found!")
        sys.exit(0)

    print(f"Found lint errors ({lint_code}):\n{lint_output}\n")

    # First, try auto-fix with ruff
    print("Attempting ruff auto-fix...")
    fix_output, fix_code = run_command("ruff check backend --fix")
    print(fix_output)

    # Check if there are remaining errors
    lint_output_after, lint_code_after = run_command("ruff check backend --output-format=text")

    if lint_code_after == 0:
        print("✓ All errors fixed by ruff --fix!")

        # Commit the changes
        print("\nCommitting auto-fixes...")
        run_command("git add backend/")

        commit_msg = """fix: auto-fix lint errors with ruff [claude-agent]

Auto-applied ruff fixes:
- Import sorting
- Unused imports removal
- Type annotation updates
- Code style fixes

Generated by Claude Agent in CI"""

        run_command(f'git commit -m "{commit_msg}"')
        print("✓ Changes committed")
        sys.exit(0)

    # If there are still errors, use Claude to help
    print(f"\n{lint_code_after} errors remaining after auto-fix")
    print("Using Claude to analyze remaining errors...")

    # Get the remaining errors with more detail
    detailed_errors, _ = run_command("ruff check backend --output-format=json")

    prompt = f"""You are helping fix Python linting errors. Here are the remaining ruff errors after auto-fix:

```
{lint_output_after}
```

Detailed error information:
```json
{detailed_errors[:5000]}
```

Please provide specific instructions for fixing these errors. For each error:
1. Identify the file and line
2. Explain what needs to be fixed
3. Provide the specific code change needed

Focus on the most common error patterns first. Keep your response concise and actionable."""

    print("Asking Claude for fix suggestions...")

    try:
        message = client.messages.create(
            model="claude-sonnet-4.5-20250929",
            max_tokens=4096,
            messages=[{"role": "user", "content": prompt}],
        )

        response = message.content[0].text
        print("\n" + "=" * 80)
        print("Claude's Analysis:")
        print("=" * 80)
        print(response)
        print("=" * 80)

        # Create a summary comment for the PR
        summary = f"""## 🤖 Claude Agent Auto-Fix Report

### Lint Errors Found
- **Total errors**: {lint_output.count('error') if 'error' in lint_output else 'multiple'}
- **Auto-fixed by ruff**: {lint_output.count('error') - lint_output_after.count('error') if 'error' in lint_output and 'error' in lint_output_after else 'some'}
- **Remaining errors**: {lint_code_after}

### Auto-Fix Actions Taken
✅ Ran `ruff check --fix` to apply automatic fixes
✅ Committed auto-fixable changes

### Remaining Issues
{lint_output_after[:2000]}

### Claude's Recommendations
{response[:2000]}

---
*Generated by Claude Agent SDK in CI*
*See `.github/scripts/auto-fix-lint.py` for implementation*
"""

        # Save summary to file for GitHub Actions to use
        with open("/tmp/auto-fix-summary.md", "w") as f:
            f.write(summary)

        print("\n✓ Summary saved to /tmp/auto-fix-summary.md")
        print("\nℹ️  Some errors require manual review. Check Claude's recommendations above.")

        # Exit with code 0 if we made progress, 1 if no changes
        if lint_code_after < lint_code:
            print(f"\n✓ Progress made: {lint_code} → {lint_code_after} errors")
            sys.exit(0)
        else:
            print("\n⚠ No progress made, manual intervention needed")
            sys.exit(1)

    except Exception as e:
        print(f"\n❌ Error calling Claude API: {e}")
        print("Falling back to basic auto-fix only")

        if lint_code_after < lint_code:
            sys.exit(0)
        else:
            sys.exit(1)


if __name__ == "__main__":
    main()
